import 'ffm_assistant_models.dart';

enum FfmAssistantCapabilityRisk { readOnly, prepare, mutation, sensitive }

class FfmAssistantCapability {
  const FfmAssistantCapability({
    required this.id,
    required this.label,
    required this.description,
    required this.risk,
    this.destination,
    this.parameterNames = const <String>[],
    this.requiresConfirmation = false,
    this.readOnly = false,
  });

  final String id;
  final String label;
  final String description;
  final FfmAssistantCapabilityRisk risk;
  final FfmAssistantDestination? destination;
  final List<String> parameterNames;
  final bool requiresConfirmation;
  final bool readOnly;

  bool get canRunWithoutConfirmation =>
      readOnly &&
      !requiresConfirmation &&
      risk == FfmAssistantCapabilityRisk.readOnly;
}

class FfmAssistantCapabilityRegistry {
  FfmAssistantCapabilityRegistry._();

  static final List<FfmAssistantCapability> all = List.unmodifiable([
    ...FfmAssistantDestination.values.map(
      (destination) => FfmAssistantCapability(
        id: 'navigate.${destination.name}',
        label: 'Buka ${_destinationName(destination)}',
        description: 'Membuka halaman ${_destinationName(destination)}.',
        risk: FfmAssistantCapabilityRisk.readOnly,
        destination: destination,
        readOnly: true,
      ),
    ),
    const FfmAssistantCapability(
      id: 'read.summary',
      label: 'Baca ringkasan',
      description: 'Membaca ringkasan saldo dan kondisi keuangan lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.summary,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.transactions',
      label: 'Baca transaksi',
      description: 'Mencari dan merangkum transaksi dari database lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.transactions,
      parameterNames: ['dateFrom', 'dateTo', 'category', 'account', 'query'],
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.budget',
      label: 'Baca anggaran',
      description: 'Membaca anggaran dan pemakaian kategori secara lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.budget,
      parameterNames: ['period', 'category'],
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.accounts',
      label: 'Baca rekening',
      description: 'Membaca daftar rekening aktif dalam bentuk ringkas.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.transactions,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.categories',
      label: 'Baca kategori',
      description: 'Membaca kategori aktif dalam bentuk ringkas.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.masterData,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.analysis',
      label: 'Baca analisa',
      description: 'Membaca ringkasan analisa keuangan lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.analysis,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.activity',
      label: 'Baca aktivitas',
      description: 'Membaca log aktivitas lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.activity,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.goals',
      label: 'Baca target',
      description: 'Membaca daftar target keuangan lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.goals,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.assets',
      label: 'Baca aset',
      description: 'Membaca daftar aset lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.assets,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.liabilities',
      label: 'Baca hutang/piutang',
      description: 'Membaca daftar hutang dan piutang lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.liabilities,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.receivable',
      label: 'Baca piutang',
      description: 'Membaca daftar piutang lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.liabilities,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.recurring',
      label: 'Baca transaksi berkala',
      description: 'Membaca jadwal transaksi berkala lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.recurringTransaction,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.reminders',
      label: 'Baca pengingat',
      description: 'Membaca daftar pengingat lokal.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.reminders,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'read.model_status',
      label: 'Periksa status Gemini Cloud',
      description: 'Memeriksa apakah key dan model Gemini Cloud sudah diuji serta tersimpan.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.intelligenceDashboard,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'draft.income',
      label: 'Siapkan pemasukan',
      description: 'Membuat draft pemasukan tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: [
        'amount',
        'date',
        'account',
        'source',
        'category',
        'note',
      ],
    ),
    const FfmAssistantCapability(
      id: 'draft.expense',
      label: 'Siapkan pengeluaran',
      description: 'Membuat draft pengeluaran tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: [
        'amount',
        'date',
        'account',
        'payee',
        'category',
        'note',
        'tags',
      ],
    ),
    const FfmAssistantCapability(
      id: 'draft.transfer',
      label: 'Siapkan transfer',
      description: 'Membuat draft transfer tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: [
        'amount',
        'date',
        'fromAccount',
        'toAccount',
        'fee',
        'note',
      ],
    ),
    const FfmAssistantCapability(
      id: 'draft.goal',
      label: 'Siapkan target',
      description: 'Membuat draft target keuangan tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.goals,
      parameterNames: ['name', 'amount', 'date'],
    ),
    const FfmAssistantCapability(
      id: 'draft.goal_deposit',
      label: 'Siapkan setoran target',
      description: 'Membuat draft setoran target tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: ['amount', 'date', 'account', 'goal', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.goal_usage',
      label: 'Siapkan penggunaan target',
      description: 'Membuat draft penggunaan target tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: ['amount', 'date', 'account', 'goal', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.goal_update',
      label: 'Siapkan perubahan target',
      description: 'Menampilkan perubahan target keuangan tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.goals,
      parameterNames: ['targetId', 'amount'],
    ),
    const FfmAssistantCapability(
      id: 'draft.goal_archive',
      label: 'Siapkan arsip target',
      description: 'Menampilkan target keuangan yang akan diarsipkan tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.goals,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.liability',
      label: 'Siapkan utang',
      description: 'Membuat draft utang tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.liabilities,
      parameterNames: ['name', 'amount', 'date', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.liability_update',
      label: 'Siapkan perubahan Hutang',
      description: 'Menampilkan perubahan metadata satu Hutang tanpa pembayaran atau perubahan sisa hutang.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.liabilities,
      parameterNames: [
        'targetId',
        'title',
        'note',
        'dueDate',
        'monthlyInstallment',
        'interestRate',
      ],
    ),
    const FfmAssistantCapability(
      id: 'draft.liability_archive',
      label: 'Siapkan arsip Hutang',
      description:
          'Menampilkan satu Hutang yang akan diarsipkan tanpa hapus permanen.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.liabilities,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.receivable',
      label: 'Siapkan piutang',
      description: 'Membuat draft piutang tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.liabilities,
      parameterNames: ['name', 'amount', 'date', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.receivable_update',
      label: 'Siapkan perubahan Piutang',
      description: 'Menampilkan perubahan metadata satu Piutang tanpa penagihan atau perubahan sisa Piutang.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.liabilities,
      parameterNames: ['targetId', 'title', 'note', 'dueDate'],
    ),
    const FfmAssistantCapability(
      id: 'draft.receivable_archive',
      label: 'Siapkan arsip Piutang',
      description:
          'Menampilkan satu Piutang yang akan diarsipkan tanpa hapus permanen.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.liabilities,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.asset',
      label: 'Siapkan aset',
      description: 'Membuat draft aset tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.assets,
      parameterNames: ['title', 'amount', 'type', 'placement', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.asset_update',
      label: 'Siapkan perubahan aset',
      description: 'Menampilkan perubahan satu aset tanpa membuat transaksi atau mutasi saldo.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.assets,
      parameterNames: [
        'targetId',
        'title',
        'amount',
        'type',
        'placement',
        'note',
      ],
    ),
    const FfmAssistantCapability(
      id: 'draft.asset_archive',
      label: 'Siapkan arsip aset',
      description:
          'Menampilkan satu aset yang akan diarsipkan tanpa hapus permanen.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.assets,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.budget_update',
      label: 'Siapkan perubahan batas Anggaran',
      description: 'Menampilkan perubahan batas satu pos Anggaran tanpa mengubah transaksi atau transfer alokasi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.budget,
      parameterNames: ['targetId', 'amount', 'operation'],
    ),
    const FfmAssistantCapability(
      id: 'draft.budget_archive',
      label: 'Siapkan arsip pos Anggaran',
      description: 'Menampilkan satu pos Anggaran yang akan diarsipkan setelah guard transaksi dan transfer alokasi diperiksa.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.budget,
      parameterNames: ['targetId', 'operation'],
    ),
    const FfmAssistantCapability(
      id: 'draft.master_data',
      label: 'Siapkan data master',
      description: 'Membuka dan mengisi draft data master tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['kind', 'name', 'values'],
    ),
    const FfmAssistantCapability(
      id: 'draft.merchant_update',
      label: 'Siapkan perubahan Toko/Tempat',
      description: 'Menampilkan perubahan nama atau keterangan satu Toko/Tempat tanpa mengubah transaksi historis.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId', 'title', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.merchant_archive',
      label: 'Siapkan arsip Toko/Tempat',
      description: 'Menampilkan satu Toko/Tempat yang akan diarsipkan tanpa mengubah transaksi historis.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.merchant_delete',
      label: 'Siapkan hapus Toko/Tempat',
      description: 'Menampilkan satu Toko/Tempat yang akan dihapus permanen dari database.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.tag_update',
      label: 'Siapkan perubahan Tag',
      description: 'Menampilkan perubahan nama satu Tag tanpa mengubah relasi transaksi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId', 'title'],
    ),
    const FfmAssistantCapability(
      id: 'draft.tag_archive',
      label: 'Siapkan arsip Tag',
      description: 'Menampilkan satu Tag yang akan diarsipkan tanpa mengubah relasi transaksi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.tag_delete',
      label: 'Siapkan hapus Tag',
      description:
          'Menampilkan satu Tag yang akan dihapus permanen dari database.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.income_source_update',
      label: 'Siapkan perubahan Sumber Pemasukan',
      description: 'Menampilkan perubahan nama atau keterangan satu Sumber Pemasukan tanpa mengubah transaksi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId', 'title', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.income_source_archive',
      label: 'Siapkan arsip Sumber Pemasukan',
      description: 'Menampilkan satu Sumber Pemasukan yang akan diarsipkan tanpa mengubah transaksi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.income_source_delete',
      label: 'Siapkan hapus Sumber Pemasukan',
      description: 'Menampilkan satu Sumber Pemasukan yang akan dihapus permanen dari database.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.category_update',
      label: 'Siapkan perubahan nama Kategori',
      description: 'Menampilkan perubahan nama satu Kategori tanpa mengubah tipe, hierarki, periode Anggaran, atau relasi data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId', 'title'],
    ),
    const FfmAssistantCapability(
      id: 'draft.category_archive',
      label: 'Siapkan arsip Kategori',
      description: 'Menampilkan satu Kategori yang akan diarsipkan setelah seluruh guard dependensi lolos.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.category_delete',
      label: 'Siapkan hapus Kategori',
      description:
          'Menampilkan satu Kategori yang akan dihapus permanen dari database.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.account_update',
      label: 'Siapkan perubahan nama Rekening',
      description: 'Menampilkan perubahan nama satu Rekening tanpa mengubah saldo awal, tipe, status, atau referensi keuangan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId', 'title'],
    ),
    const FfmAssistantCapability(
      id: 'draft.account_archive',
      label: 'Siapkan arsip Rekening',
      description: 'Menampilkan arsip satu Rekening hanya setelah guard seluruh referensi keuangan lolos.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.account_delete',
      label: 'Siapkan hapus Rekening',
      description:
          'Menampilkan satu Rekening yang akan dihapus permanen dari database.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.masterData,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.reminder',
      label: 'Siapkan pengingat',
      description: 'Membuat draft pengingat tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.reminders,
      parameterNames: ['title', 'date', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.reminder_archive',
      label: 'Siapkan arsip pengingat',
      description: 'Menampilkan pengingat yang akan dinonaktifkan tanpa menghapus history.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.reminders,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.activity',
      label: 'Siapkan aktivitas',
      description: 'Membuat draft aktivitas tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['title', 'category', 'date', 'notes'],
    ),
    const FfmAssistantCapability(
      id: 'draft.daily_note',
      label: 'Siapkan Catatan Harian',
      description: 'Membuat preview Catatan Harian tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['title', 'body', 'date'],
    ),
    const FfmAssistantCapability(
      id: 'draft.daily_note_archive',
      label: 'Siapkan arsip Catatan Harian',
      description: 'Menampilkan satu Catatan Harian yang akan diarsipkan tanpa menghapusnya.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.task',
      label: 'Siapkan Tugas',
      description: 'Membuat preview Tugas tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['title', 'note', 'date'],
    ),
    const FfmAssistantCapability(
      id: 'draft.task_update',
      label: 'Siapkan perubahan Tugas',
      description: 'Menampilkan perubahan Tugas tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId', 'title', 'note', 'date'],
    ),
    const FfmAssistantCapability(
      id: 'draft.task_complete',
      label: 'Siapkan penyelesaian Tugas',
      description:
          'Menampilkan Tugas yang akan ditandai selesai tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.task_reopen',
      label: 'Siapkan buka kembali Tugas',
      description: 'Menampilkan Tugas selesai yang akan dibuka kembali tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.task_archive',
      label: 'Siapkan arsip Tugas',
      description: 'Menampilkan Tugas yang akan diarsipkan tanpa menghapusnya.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.reminder_update',
      label: 'Siapkan perubahan pengingat',
      description: 'Menampilkan perubahan judul atau waktu satu pengingat tanpa menjadwalkan ulang sebelum konfirmasi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.reminders,
      parameterNames: ['targetId', 'title', 'date', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.routine',
      label: 'Siapkan Rutinitas',
      description:
          'Membuat preview Rutinitas tanpa menyimpan atau membuat pengingat.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['title', 'note', 'weekdays'],
    ),
    const FfmAssistantCapability(
      id: 'draft.routine_update',
      label: 'Siapkan perubahan Rutinitas',
      description:
          'Menampilkan satu Rutinitas yang akan diperbarui tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId', 'title', 'note', 'weekdays'],
    ),
    const FfmAssistantCapability(
      id: 'draft.routine_mark_complete',
      label: 'Siapkan tanda Rutinitas hari ini',
      description: 'Menampilkan satu Rutinitas yang akan ditandai selesai hari ini tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId', 'date'],
    ),
    const FfmAssistantCapability(
      id: 'draft.routine_unmark_complete',
      label: 'Siapkan pembatalan tanda Rutinitas',
      description: 'Menampilkan satu tanda Rutinitas hari ini yang akan dibatalkan secara eksplisit.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId', 'date'],
    ),
    const FfmAssistantCapability(
      id: 'draft.routine_activate',
      label: 'Siapkan aktivasi Rutinitas',
      description: 'Menampilkan satu Rutinitas yang akan diaktifkan tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.routine_deactivate',
      label: 'Siapkan penonaktifan Rutinitas',
      description: 'Menampilkan satu Rutinitas yang akan dinonaktifkan tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.routine_archive',
      label: 'Siapkan arsip Rutinitas',
      description: 'Menampilkan satu Rutinitas yang akan diarsipkan tanpa hapus permanen.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.schedule',
      label: 'Siapkan Jadwal',
      description:
          'Membuat preview agenda Jadwal tanpa menyimpan atau membuat alarm.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: [
        'title',
        'date',
        'note',
        'isAllDay',
        'startMinutes',
        'endMinutes',
      ],
    ),
    const FfmAssistantCapability(
      id: 'draft.schedule_update',
      label: 'Siapkan perubahan Jadwal',
      description: 'Menampilkan satu agenda Jadwal yang akan diperbarui tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: [
        'targetId',
        'title',
        'date',
        'note',
        'isAllDay',
        'startMinutes',
        'endMinutes',
      ],
    ),
    const FfmAssistantCapability(
      id: 'draft.schedule_archive',
      label: 'Siapkan arsip Jadwal',
      description: 'Menampilkan satu agenda Jadwal yang akan diarsipkan tanpa hapus permanen.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.recurring_transaction_update',
      label: 'Siapkan perubahan Transaksi Berkala',
      description: 'Menampilkan perubahan nama atau catatan satu aturan berkala tanpa menjalankan jadwal atau membuat transaksi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.recurringTransaction,
      parameterNames: ['targetId', 'title', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.recurring_transaction_archive',
      label: 'Siapkan nonaktifkan Transaksi Berkala',
      description: 'Menampilkan satu aturan berkala yang akan dinonaktifkan tanpa mengubah riwayat atau transaksi.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.recurringTransaction,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'mutate.save_draft',
      label: 'Simpan draft',
      description: 'Menyimpan draft yang telah ditinjau ke database lokal.',
      risk: FfmAssistantCapabilityRisk.mutation,
      requiresConfirmation: true,
    ),
    const FfmAssistantCapability(
      id: 'draft.transaction_update',
      label: 'Siapkan perubahan transaksi',
      description:
          'Menampilkan perubahan transaksi yang diusulkan tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: ['targetId', 'amount', 'note', 'date'],
    ),
    const FfmAssistantCapability(
      id: 'draft.transaction_archive',
      label: 'Siapkan arsip transaksi',
      description:
          'Menampilkan transaksi yang akan diarsipkan tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.transaction_delete',
      label: 'Siapkan hapus transaksi',
      description: 'Menampilkan transaksi yang akan dihapus sebelum konfirmasi eksplisit.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.transactions,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.activity_archive',
      label: 'Siapkan arsip aktivitas',
      description: 'Menampilkan aktivitas selesai yang akan diarsipkan tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.activity_delete',
      label: 'Siapkan hapus aktivitas',
      description: 'Menampilkan aktivitas selesai beserta dampak hapusnya sebelum konfirmasi eksplisit.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.activity_finish',
      label: 'Siapkan selesai aktivitas',
      description:
          'Menampilkan aktivitas yang akan diselesaikan tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId'],
    ),
    const FfmAssistantCapability(
      id: 'draft.activity_update',
      label: 'Siapkan update aktivitas',
      description: 'Menambah checkpoint atau catatan pada aktivitas yang sedang berjalan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId', 'label', 'place', 'note'],
    ),
    const FfmAssistantCapability(
      id: 'draft.activity_edit',
      label: 'Siapkan edit aktivitas',
      description: 'Mengubah judul atau kategori aktivitas tanpa menyimpan.',
      risk: FfmAssistantCapabilityRisk.prepare,
      destination: FfmAssistantDestination.activity,
      parameterNames: ['targetId', 'title', 'category'],
    ),
    const FfmAssistantCapability(
      id: 'verify.saved_draft',
      label: 'Verifikasi hasil simpan',
      description: 'Membaca kembali hasil mutation untuk memastikan perubahan benar-benar tersimpan.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.transaction_mutation',
      label: 'Verifikasi perubahan transaksi',
      description: 'Membaca kembali status transaksi setelah perubahan, arsip, atau hapus.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.activity_mutation',
      label: 'Verifikasi perubahan aktivitas',
      description: 'Membaca kembali status aktivitas setelah arsip atau hapus.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.asset_mutation',
      label: 'Verifikasi perubahan aset',
      description: 'Membaca kembali aset setelah perubahan atau arsip lunak.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.liability_mutation',
      label: 'Verifikasi perubahan Hutang',
      description: 'Membaca kembali Hutang setelah perubahan atau arsip lunak.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.budget_mutation',
      label: 'Verifikasi perubahan anggaran',
      description:
          'Membaca kembali anggaran setelah perubahan batas atau arsip.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.daily_note_mutation',
      label: 'Verifikasi Catatan Harian',
      description: 'Membaca kembali Catatan Harian setelah simpan atau arsip.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.task_mutation',
      label: 'Verifikasi Tugas',
      description:
          'Membaca kembali Tugas setelah simpan, ubah status, atau arsip.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.routine_mutation',
      label: 'Verifikasi Rutinitas',
      description:
          'Membaca kembali Rutinitas atau tanda hariannya setelah perubahan.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.schedule_mutation',
      label: 'Verifikasi Jadwal',
      description: 'Membaca kembali agenda Jadwal setelah simpan, perubahan, atau arsip.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.goal_mutation',
      label: 'Verifikasi perubahan target',
      description: 'Membaca kembali target setelah perubahan atau arsip.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.reminder_mutation',
      label: 'Verifikasi arsip pengingat',
      description: 'Membaca kembali status pengingat setelah dinonaktifkan.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.receivable_mutation',
      label: 'Verifikasi perubahan Piutang',
      description: 'Membaca kembali Piutang setelah perubahan metadata atau arsip lunak.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.recurring_transaction_mutation',
      label: 'Verifikasi Transaksi Berkala',
      description: 'Membaca kembali aturan berkala setelah perubahan metadata atau dinonaktifkan.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.merchant_mutation',
      label: 'Verifikasi Toko/Tempat',
      description: 'Membaca kembali Toko/Tempat setelah perubahan metadata, arsip lunak, atau hapus permanen.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.tag_mutation',
      label: 'Verifikasi Tag',
      description: 'Membaca kembali Tag setelah perubahan nama, arsip lunak, atau hapus permanen.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.income_source_mutation',
      label: 'Verifikasi Sumber Pemasukan',
      description: 'Membaca kembali Sumber Pemasukan setelah perubahan metadata, arsip lunak, atau hapus permanen.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.category_mutation',
      label: 'Verifikasi Kategori',
      description: 'Membaca kembali Kategori setelah perubahan nama, arsip lunak yang lolos guard, atau hapus permanen.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'verify.account_mutation',
      label: 'Verifikasi Rekening',
      description: 'Membaca kembali Rekening setelah perubahan nama, arsip lunak yang lolos guard referensi, atau hapus permanen.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      readOnly: true,
    ),
    const FfmAssistantCapability(
      id: 'mutate.update',
      label: 'Perbarui data',
      description: 'Memperbarui data aplikasi yang dipilih pengguna.',
      risk: FfmAssistantCapabilityRisk.mutation,
      requiresConfirmation: true,
    ),
    const FfmAssistantCapability(
      id: 'mutate.archive',
      label: 'Arsipkan data',
      description: 'Mengarsipkan data yang dipilih pengguna.',
      risk: FfmAssistantCapabilityRisk.mutation,
      requiresConfirmation: true,
    ),
    const FfmAssistantCapability(
      id: 'sensitive.delete',
      label: 'Hapus data',
      description: 'Menghapus data setelah konfirmasi eksplisit.',
      risk: FfmAssistantCapabilityRisk.sensitive,
      requiresConfirmation: true,
    ),
    const FfmAssistantCapability(
      id: 'model.status',
      label: 'Periksa Gemini Cloud',
      description:
          'Memeriksa status key dan model Gemini Cloud tanpa mengubah data.',
      risk: FfmAssistantCapabilityRisk.readOnly,
      destination: FfmAssistantDestination.intelligenceDashboard,
      readOnly: true,
    ),
  ]);

  static String _destinationName(FfmAssistantDestination destination) =>
      FfmAssistantCatalog.findByDestination(destination)?.name ??
      destination.name;

  static FfmAssistantCapability? find(String id) {
    for (final capability in all) {
      if (capability.id == id) return capability;
    }
    return null;
  }

  static List<FfmAssistantCapability> forDestination(
    FfmAssistantDestination destination,
  ) => all
      .where((capability) => capability.destination == destination)
      .toList(growable: false);
}
